const fs = require('fs');

const products = [
    {
        id: "tws-earphones-pro",
        name: "Pro TWS Wireless Earbuds",
        slug: "pro-tws-wireless-earbuds-price-kenya",
        category: "Audio",
        image: "/assets/images/tws-earphones.png",
        badge: "Bestseller",
        price: 1800,
        oldPrice: 3500,
        discount: "48% OFF",
        rating: 5,
        reviews: "12k+",
        store: "AliExpress",
        description: "Experience crystal clear audio with active noise cancellation and 24-hour battery life. The ultimate everyday carry for music lovers."
    },
    {
        id: "shockproof-phone-case",
        name: "Rugged Armor Phone Case",
        slug: "rugged-armor-phone-case-price-kenya",
        category: "Accessories",
        image: "/assets/images/phone-case.png",
        badge: "Essential",
        price: 450,
        oldPrice": 900,
        discount: "50% OFF",
        rating: 4,
        reviews: "8.4k",
        store: "AliExpress",
        description: "Military-grade drop protection for your smartphone. Features carbon fiber textures and a built-in kickstand for media viewing."
    },
    {
        id: "magnetic-charging-cable",
        name: "3-in-1 Magnetic Charging Cable",
        slug: "magnetic-charging-cable-price-kenya",
        category: "Accessories",
        image: "/assets/images/placeholder.svg",
        badge: "Viral",
        price: 550,
        oldPrice: 1200,
        discount: "54% OFF",
        rating: 5,
        reviews: "22k+",
        store: "AliExpress",
        description: "Charge any device (Type-C, Micro USB, Lightning) with one cable. The magnetic snap-on connector prevents port damage and tangled wires."
    },
    {
        id: "mini-bluetooth-speaker",
        name: "Waterproof Mini Bluetooth Speaker",
        slug: "waterproof-mini-bluetooth-speaker-price-kenya",
        category: "Audio",
        image: "/assets/images/placeholder.svg",
        badge: "Top Rated",
        price: 1500,
        oldPrice": 2800,
        discount: "46% OFF",
        rating: 4,
        reviews: "5.1k",
        store: "AliExpress",
        description: "Take the party anywhere. This ultra-portable speaker delivers punchy bass, connects instantly via Bluetooth 5.0, and is fully IPX7 waterproof."
    },
    {
        id: "led-ring-light-tripod",
        name: "10-inch LED Ring Light + Tripod",
        slug: "led-ring-light-tripod-price-kenya",
        category: "Tech",
        image: "/assets/images/placeholder.svg",
        badge: "Creator Gear",
        price: 2200,
        oldPrice: 4000,
        discount: "45% OFF",
        rating: 5,
        reviews: "18k+",
        store: "AliExpress",
        description: "The essential setup for TikTok and YouTube creators. Features 3 color modes and 10 brightness levels to give you perfect studio lighting at home."
    },
    {
        id: "360-car-phone-holder",
        name: "360° Dashboard Car Phone Holder",
        slug: "360-car-phone-holder-price-kenya",
        category: "Auto",
        image: "/assets/images/placeholder.svg",
        badge: "Hot Deal",
        price: 650,
        oldPrice: 1500,
        discount: "56% OFF",
        rating: 4,
        reviews: "9.2k",
        store: "AliExpress",
        description: "Navigate Nairobi traffic safely. This heavy-duty suction mount keeps your phone securely in place even on bumpy roads."
    },
    {
        id: "rgb-led-strip-lights",
        name: "Smart RGB LED Strip Lights (5M)",
        slug: "smart-rgb-led-strip-lights-price-kenya",
        category: "Home",
        image: "/assets/images/placeholder.svg",
        badge: "Trending",
        price: 1200,
        oldPrice: 2500,
        discount: "52% OFF",
        rating: 5,
        reviews: "31k+",
        store: "AliExpress",
        description: "Transform your bedroom or living room instantly. Control millions of colors directly from your smartphone or sync them to the beat of your music."
    },
    {
        id: "aluminum-laptop-stand",
        name: "Foldable Aluminum Laptop Stand",
        slug: "foldable-aluminum-laptop-stand-price-kenya",
        category: "Tech",
        image: "/assets/images/placeholder.svg",
        badge: "Pro Choice",
        price: 1800,
        oldPrice: 3500,
        discount: "48% OFF",
        rating: 5,
        reviews: "14k+",
        store: "AliExpress",
        description: "Improve your posture and keep your laptop cool. This premium metal stand is fully adjustable, incredibly sturdy, and folds flat for travel."
    },
    {
        id: "lace-front-wig",
        name: "Premium Lace Front Human Hair Wig",
        slug: "lace-front-human-hair-wig-price-kenya",
        category: "Beauty",
        image: "/assets/images/placeholder.svg",
        badge: "Best Seller",
        price: 8500,
        oldPrice: 15000,
        discount: "43% OFF",
        rating: 4,
        reviews: "6.7k",
        store: "AliExpress",
        description: "Achieve a flawless natural look with 100% human hair. Pre-plucked hairline, tangle-free, and can be dyed or styled exactly how you want it."
    },
    {
        id: "nail-art-gel-kit",
        name: "Professional Gel Polish Nail Kit",
        slug: "professional-gel-polish-nail-kit-price-kenya",
        category: "Beauty",
        image: "/assets/images/placeholder.svg",
        badge: "Value Pack",
        price: 1800,
        oldPrice: 3500,
        discount: "48% OFF",
        rating: 5,
        reviews: "11k+",
        store: "AliExpress",
        description: "Skip the salon. This complete kit includes a UV LED lamp, multiple vibrant gel colors, base/top coats, and professional manicure tools."
    },
    {
        id: "3d-eyelash-extensions",
        name: "3D Mink Eyelash Extensions",
        slug: "3d-mink-eyelash-extensions-price-kenya",
        category: "Beauty",
        image: "/assets/images/placeholder.svg",
        badge: "Viral",
        price: 450,
        oldPrice: 1000,
        discount: "55% OFF",
        rating: 4,
        reviews: "25k+",
        store: "AliExpress",
        description: "Instantly elevate your look. These lightweight, reusable, and cruelty-free lashes provide dramatic volume and a natural flutter."
    },
    {
        id: "nano-facial-steamer",
        name: "Nano Ionic Facial Steamer",
        slug: "nano-ionic-facial-steamer-price-kenya",
        category: "Beauty",
        image: "/assets/images/placeholder.svg",
        badge: "Self Care",
        price: 2200,
        oldPrice: 4000,
        discount: "45% OFF",
        rating: 5,
        reviews: "8.3k",
        store: "AliExpress",
        description: "Bring the spa home. This device generates ultra-fine nano steam that deeply penetrates the skin to unclog pores and improve hydration."
    },
    {
        id: "ultrasonic-blackhead-remover",
        name: "Ultrasonic Blackhead Vacuum",
        slug: "ultrasonic-blackhead-vacuum-price-kenya",
        category: "Beauty",
        image: "/assets/images/placeholder.svg",
        badge: "Hot Deal",
        price: 1500,
        oldPrice: 3000,
        discount: "50% OFF",
        rating: 4,
        reviews: "19k+",
        store: "AliExpress",
        description: "Clear your skin effortlessly. Features multiple suction levels and interchangeable heads to safely remove blackheads, grease, and acne."
    },
    {
        id: "vitamin-c-serum",
        name: "Brightening Vitamin C Serum (30ml)",
        slug: "brightening-vitamin-c-serum-price-kenya",
        category: "Beauty",
        image: "/assets/images/placeholder.svg",
        badge: "Essential",
        price: 950,
        oldPrice: 1800,
        discount: "47% OFF",
        rating: 5,
        reviews: "33k+",
        store: "AliExpress",
        description: "Achieve a glowing, even skin tone. This potent antioxidant formula fades dark spots, reduces wrinkles, and boosts collagen production."
    },
    {
        id: "portable-mini-blender",
        name: "USB Portable Mini Blender",
        slug: "usb-portable-mini-blender-price-kenya",
        category: "Home",
        image: "/assets/images/placeholder.svg",
        badge: "Fitness",
        price: 1800,
        oldPrice: 3500,
        discount: "48% OFF",
        rating: 4,
        reviews: "15k+",
        store: "AliExpress",
        description: "Make fresh smoothies anywhere. This powerful, rechargeable blender is perfect for the gym, office, or travel. Self-cleaning and BPA-free."
    },
    {
        id: "acrylic-storage-organizer",
        name: "Clear Acrylic Makeup Organizer",
        slug: "clear-acrylic-makeup-organizer-price-kenya",
        category: "Home",
        image: "/assets/images/placeholder.svg",
        badge: "Trending",
        price: 1200,
        oldPrice: 2500,
        discount: "52% OFF",
        rating: 5,
        reviews: "9.5k",
        store: "AliExpress",
        description: "Declutter your vanity space. This elegant, transparent storage system features multiple drawers and compartments for all your cosmetics."
    },
    {
        id: "uv-mosquito-killer",
        name: "UV Mosquito Killer Lamp",
        slug: "uv-mosquito-killer-lamp-price-kenya",
        category: "Home",
        image: "/assets/images/placeholder.svg",
        badge: "Must Have",
        price: 900,
        oldPrice: 2000,
        discount: "55% OFF",
        rating: 4,
        reviews: "21k+",
        store: "AliExpress",
        description: "Sleep peacefully without toxic sprays. This quiet device uses UV light to attract and trap mosquitoes efficiently. Plugs directly into USB."
    },
    {
        id: "solar-garden-lights",
        name: "Waterproof Solar Garden Lights (4 Pack)",
        slug: "waterproof-solar-garden-lights-price-kenya",
        category: "Solar",
        image: "/assets/images/placeholder.svg",
        badge: "Eco-Friendly",
        price: 1500,
        oldPrice: 3000,
        discount: "50% OFF",
        rating: 5,
        reviews: "12k+",
        store: "AliExpress",
        description: "Illuminate your outdoor spaces for free. These durable, auto-on LED lights charge during the day and provide brilliant security lighting at night."
    },
    {
        id: "digital-kitchen-scale",
        name: "High Precision Digital Kitchen Scale",
        slug: "high-precision-digital-kitchen-scale-price-kenya",
        category: "Home",
        image: "/assets/images/placeholder.svg",
        badge: "Essential",
        price: 650,
        oldPrice: 1500,
        discount: "56% OFF",
        rating: 5,
        reviews: "28k+",
        store: "AliExpress",
        description: "Take the guesswork out of cooking and baking. Features a sleek stainless steel surface, LCD display, and measures up to 5kg with gram precision."
    },
    {
        id: "wireless-baby-monitor",
        name: "Smart Wireless Video Baby Monitor",
        slug: "smart-wireless-video-baby-monitor-price-kenya",
        category: "Baby",
        image: "/assets/images/placeholder.svg",
        badge: "Peace of Mind",
        price: 4500,
        oldPrice: 8000,
        discount: "43% OFF",
        rating: 5,
        reviews: "7.2k",
        store: "AliExpress",
        description: "Watch your little one from anywhere. Features night vision, two-way audio, temperature monitoring, and a dedicated high-res parent display unit."
    },
    {
        id: "ergonomic-baby-carrier",
        name: "Ergonomic Baby Carrier Wrap",
        slug: "ergonomic-baby-carrier-wrap-price-kenya",
        category: "Baby",
        image: "/assets/images/placeholder.svg",
        badge: "Top Rated",
        price: 2200,
        oldPrice: 4500,
        discount: "51% OFF",
        rating: 4,
        reviews: "11k+",
        store: "AliExpress",
        description: "Keep your hands free and your baby close. This breathable, multi-position carrier provides essential lumbar support and is adjustable for all sizes."
    },
    {
        id: "nursing-pillow",
        name: "Comfort Maternity Nursing Pillow",
        slug: "comfort-maternity-nursing-pillow-price-kenya",
        category: "Baby",
        image: "/assets/images/placeholder.svg",
        badge: "Essential",
        price: 1800,
        oldPrice: 3500,
        discount: "48% OFF",
        rating: 5,
        reviews: "5.5k",
        store: "AliExpress",
        description: "Make feeding time comfortable. This uniquely shaped pillow supports your baby while relieving strain on your back, neck, and arms."
    },
    {
        id: "smart-bottle-warmer",
        name: "Smart Digital Baby Bottle Warmer",
        slug: "smart-digital-baby-bottle-warmer-price-kenya",
        category: "Baby",
        image: "/assets/images/placeholder.svg",
        badge: "Hot Deal",
        price: 2500,
        oldPrice: 4500,
        discount: "44% OFF",
        rating: 4,
        reviews: "8.9k",
        store: "AliExpress",
        description: "Warm milk quickly and evenly without destroying nutrients. Features precise temperature control, a sterilizing function, and auto shut-off."
    },
    {
        id: "urban-streetwear-sneakers",
        name: "Urban Streetwear Fashion Sneakers",
        slug: "urban-streetwear-fashion-sneakers-price-kenya",
        category: "Fashion",
        image: "/assets/images/placeholder.svg",
        badge: "Trending",
        price: 3500,
        oldPrice: 6500,
        discount: "46% OFF",
        rating: 4,
        reviews: "16k+",
        store: "AliExpress",
        description: "Step out in style. These ultra-comfortable, breathable, and highly durable sneakers feature modern street aesthetics perfect for everyday wear."
    },
    {
        id: "premium-waist-trainer",
        name: "Neoprene Sweat Waist Trainer",
        slug: "neoprene-sweat-waist-trainer-price-kenya",
        category: "Fashion",
        image: "/assets/images/placeholder.svg",
        badge: "Fitness",
        price: 1200,
        oldPrice: 2800,
        discount: "57% OFF",
        rating: 5,
        reviews: "45k+",
        store: "AliExpress",
        description: "Maximize your workouts. This adjustable, high-compression belt increases core temperature to burn fat faster while providing excellent back support."
    },
    {
        id: "vintage-polarized-sunglasses",
        name: "Vintage Polarized Sunglasses",
        slug: "vintage-polarized-sunglasses-price-kenya",
        category: "Fashion",
        image: "/assets/images/placeholder.svg",
        badge: "Summer Style",
        price: 650,
        oldPrice: 1500,
        discount: "56% OFF",
        rating: 5,
        reviews: "38k+",
        store: "AliExpress",
        description: "Protect your eyes and look incredible. These premium polarized lenses block 100% of UVA/UVB rays and eliminate glare for crystal clear vision."
    },
    {
        id: "vibrant-ankara-fabric",
        name: "Premium Ankara Print Fabric (6 Yards)",
        slug: "premium-ankara-print-fabric-price-kenya",
        category: "Fashion",
        image: "/assets/images/placeholder.svg",
        badge: "Culture",
        price: 1800,
        oldPrice: 3500,
        discount: "48% OFF",
        rating: 4,
        reviews: "9.1k",
        store: "AliExpress",
        description: "High-quality, 100% cotton African wax print. Perfect for custom tailoring dresses, shirts, and accessories. Vibrant colors that won't fade after washing."
    },
    {
        id: "athletic-compression-socks",
        name: "Athletic Compression Socks",
        slug: "athletic-compression-socks-price-kenya",
        category: "Fashion",
        image: "/assets/images/placeholder.svg",
        badge: "Health",
        price: 450,
        oldPrice: 1000,
        discount: "55% OFF",
        rating: 5,
        reviews: "27k+",
        store: "AliExpress",
        description: "Improve circulation and reduce leg fatigue. Essential for nurses, runners, or anyone who spends long hours on their feet or traveling."
    }
];

const existingData = JSON.parse(fs.readFileSync('products.json', 'utf8'));

// Only add items that don't already exist
const newItems = products.filter(p => !existingData.some(existing => existing.id === p.id));
const combinedData = [...existingData, ...newItems];

fs.writeFileSync('products.json', JSON.stringify(combinedData, null, 4));
console.log(`Successfully added ${newItems.length} new items to products.json`);
